In [64]:
import torch

In [65]:
x = torch.tensor(2.0, requires_grad=True)

In [66]:
x

tensor(2., requires_grad=True)

In [67]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [68]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [69]:
type(y)

torch.Tensor

In [70]:
y.backward()

In [71]:
x.grad

tensor(93.)

In [72]:
x = torch.tensor([[1.,2.,3], [3.,2.,1]], requires_grad=True)

In [73]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [74]:
y = 3*x+2

In [75]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [76]:
z = 2*y**2

In [77]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [78]:
out = z.mean()

In [79]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [80]:
out.backward()

In [81]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])


In [82]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [83]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])