In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.1.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
print(arr)

[1 2 3 4 5]


In [12]:
x = torch.from_numpy(arr)

In [13]:
x

tensor([1, 2, 3, 4, 5])

In [14]:
type(x)

torch.Tensor

In [16]:
x.dtype

torch.int64

In [17]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [18]:
arr2d = np.arange(0., 12.)

In [19]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [20]:
arr2d = arr2d.reshape(4,3)

In [21]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [22]:
x2 = torch.from_numpy(arr2d)

In [23]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [24]:
type(x2)

torch.Tensor

In [25]:
x2.dtype

torch.float64

In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
arr[0] = 99

In [28]:
x

tensor([99,  2,  3,  4,  5])

In [29]:
arr

array([99,  2,  3,  4,  5])

In [30]:
new_arr = np.arange(0, 10)

In [31]:
new_tensor = torch.tensor(new_arr)

In [32]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
other_new_tensor = torch.from_numpy(new_arr)

In [35]:
other_new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
new_arr[0] = 99

In [37]:
new_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [38]:
other_new_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [39]:
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# torch.as_tensor and torch.from_numpy "retains the links to the original values between the np array and the tensor and the" torch.tensor "does not as it create a copy in memory so the original value is not affected"