In [4]:
import torch

In [5]:
import numpy as np

In [6]:
torch.__version__

'2.1.0'

In [7]:
arr = np.array([1,2,3,4,5])

In [8]:
arr.dtype

dtype('int64')

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
print(arr)

[1 2 3 4 5]


In [12]:
x = torch.from_numpy(arr)

In [13]:
x

tensor([1, 2, 3, 4, 5])

In [14]:
type(x)

torch.Tensor

In [15]:
x.dtype

torch.int64

In [16]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [17]:
arr2d = np.arange(0., 12.)

In [18]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [19]:
arr2d = arr2d.reshape(4,3)

In [20]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [21]:
x2 = torch.from_numpy(arr2d)

In [22]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [23]:
type(x2)

torch.Tensor

In [24]:
x2.dtype

torch.float64

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr[0] = 99

In [27]:
x

tensor([99,  2,  3,  4,  5])

In [28]:
arr

array([99,  2,  3,  4,  5])

In [29]:
new_arr = np.arange(0, 10)

In [30]:
new_tensor = torch.tensor(new_arr)

In [31]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
other_new_tensor = torch.from_numpy(new_arr)

In [34]:
other_new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
new_arr[0] = 99

In [36]:
new_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [37]:
other_new_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [38]:
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# torch.as_tensor and torch.from_numpy "retains the links to the original values between the np array and the tensor and the" torch.tensor "does not as it create a copy in memory so the original value is not affected"

In [40]:
new_arr = np.array([1,2,3])

In [41]:
new_arr.dtype

dtype('int64')

In [42]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [43]:
torch.tensor(new_arr).dtype

torch.int64

In [44]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [45]:
torch.Tensor(new_arr).dtype

torch.float32

In [46]:
torch.empty(2,2)

tensor([[0.0000e+00, 4.5845e-41],
        [1.3002e+22, 3.3088e-09]])

In [47]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [48]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [49]:
torch.ones(4,3, dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [50]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [51]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [52]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [53]:
my_tensor = torch.tensor([1,2,3])

In [54]:
my_tensor.dtype

torch.int64

In [55]:
my_tensor = my_tensor.type(torch.int32)

In [56]:
my_tensor.dtype

torch.int32

In [57]:
torch.rand(4,3)

tensor([[0.5384, 0.4118, 0.0533],
        [0.0099, 0.3000, 0.0546],
        [0.3849, 0.1681, 0.4502],
        [0.7788, 0.3115, 0.8520]])

In [58]:
torch.randn(4,3)

tensor([[ 0.0782, -0.1622,  1.2386],
        [ 1.1053,  0.9413,  1.5198],
        [ 0.1104,  0.7181,  0.3675],
        [ 0.3702, -0.3915,  0.1728]])

In [59]:
torch.randint(0,10,(5,5))

tensor([[7, 2, 8, 2, 3],
        [1, 3, 4, 7, 4],
        [7, 2, 3, 0, 7],
        [1, 4, 4, 0, 3],
        [6, 4, 7, 2, 2]])

In [60]:
torch.randint(low=0,high=11,size=(5,5))

tensor([[ 0,  3,  1,  0, 10],
        [ 6,  7,  1,  4,  4],
        [ 1,  1,  6,  9,  3],
        [ 9,  5,  0,  6,  4],
        [ 6,  6,  7,  6, 10]])

In [61]:
x = torch.zeros(2,5)

In [62]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [63]:
x.shape

torch.Size([2, 5])

In [64]:
torch.rand_like(x)

tensor([[0.2686, 0.6460, 0.0993, 0.1828, 0.4397],
        [0.2519, 0.9743, 0.1343, 0.4351, 0.9875]])

In [65]:
torch.randn_like(x)

tensor([[-1.4457,  0.4640,  0.2000,  0.1113, -0.1463],
        [ 1.1077, -0.1166, -0.3333, -0.9542,  0.5205]])

In [67]:
torch.randint_like(x,0,11)

tensor([[ 7., 10.,  7.,  6.,  0.],
        [ 5.,  5.,  5.,  0., 10.]])

In [68]:
torch.randint_like(x,low=0,high=11)

tensor([[ 7., 10.,  2.,  9.,  6.],
        [ 2.,  0.,  4.,  1.,  8.]])

In [81]:
torch. manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [82]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])