In [51]:
import torch
import numpy as np

In [52]:
x = torch.arange(6).reshape(3,2)

In [53]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [54]:
x[1,1]

tensor(3)

In [55]:
x[1,1].dtype

torch.int64

In [56]:
type(x[1,1])

torch.Tensor

In [57]:
x[:,1]

tensor([1, 3, 5])

In [58]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [59]:
x = torch.arange(10)

In [60]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [62]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [64]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x = x.view(2,5)

In [66]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [67]:
x = torch.arange(10)

In [68]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
z = x.view(2,5)

In [70]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [72]:
x[0] = 9999

In [73]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [74]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [75]:
x = torch.arange(10)

In [76]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x.shape

torch.Size([10])

In [78]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [79]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [80]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [81]:
a = torch.tensor([1.,2.,3.])

In [82]:
a

tensor([1., 2., 3.])

In [83]:
b = torch.tensor([4.,5.,6.])

In [84]:
b

tensor([4., 5., 6.])

In [85]:
a + b

tensor([5., 7., 9.])

In [86]:
torch.add(a, b)

tensor([5., 7., 9.])

In [89]:
a = a + b

In [90]:
a

tensor([5., 7., 9.])

In [91]:
a.mul(b)

tensor([20., 35., 54.])

In [92]:
a

tensor([5., 7., 9.])

In [93]:
a.mul_(b)

tensor([20., 35., 54.])

In [94]:
a

tensor([20., 35., 54.])