In [165]:
import torch
import numpy as np

In [166]:
x = torch.arange(6).reshape(3,2)

In [167]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [168]:
x[1,1]

tensor(3)

In [169]:
x[1,1].dtype

torch.int64

In [170]:
type(x[1,1])

torch.Tensor

In [171]:
x[:,1]

tensor([1, 3, 5])

In [172]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [173]:
x = torch.arange(10)

In [174]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [176]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [178]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
x = x.view(2,5)

In [180]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [181]:
x = torch.arange(10)

In [182]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
z = x.view(2,5)

In [184]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [186]:
x[0] = 9999

In [187]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [188]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [189]:
x = torch.arange(10)

In [190]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
x.shape

torch.Size([10])

In [192]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [193]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [194]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [195]:
a = torch.tensor([1.,2.,3.])

In [196]:
a

tensor([1., 2., 3.])

In [197]:
b = torch.tensor([4.,5.,6.])

In [198]:
b

tensor([4., 5., 6.])

In [199]:
a + b

tensor([5., 7., 9.])

In [200]:
torch.add(a, b)

tensor([5., 7., 9.])

In [201]:
a = a + b

In [202]:
a

tensor([5., 7., 9.])

In [203]:
a.mul(b)

tensor([20., 35., 54.])

In [204]:
a

tensor([5., 7., 9.])

In [205]:
a.mul_(b)

tensor([20., 35., 54.])

In [206]:
a

tensor([20., 35., 54.])

In [207]:
a = torch.tensor([1.,2.,3.])

In [208]:
a

tensor([1., 2., 3.])

In [209]:
b

tensor([4., 5., 6.])

In [210]:
a * b

tensor([ 4., 10., 18.])

In [211]:
c = torch.tensor([7.])

In [212]:
c

tensor([7.])

In [213]:
a.mul(b)

tensor([ 4., 10., 18.])

In [214]:
a.dot(b)

tensor(32.)

In [216]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [217]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [218]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [219]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [220]:
a.shape

torch.Size([2, 3])

In [221]:
b.shape

torch.Size([3, 2])

In [222]:
torch.mm(a, b)

tensor([[56, 62],
        [80, 89]])

In [223]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [224]:
x = torch.tensor([2.,3.,4.,5.])

In [225]:
x

tensor([2., 3., 4., 5.])

In [227]:
# Euclidean norm or magnitude of a vector
x.norm()

tensor(7.3485)

In [229]:
x.numel()

4

In [230]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [231]:
len(a)

2

In [233]:
a.numel()

6