In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
type(mylist)

list

In [7]:
arr = np.array(mylist)

In [8]:
arr

array([1, 2, 3])

In [9]:
mylist=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
mymatrix = np.array(mylist)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mymatrix.shape

(3, 3)

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [18]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [19]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [20]:
[1,1,1,1] * 10

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [21]:
[1,1,1,1] + 10

TypeError: can only concatenate list (not "int") to list

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5)

array([0.52374401, 0.32196892, 0.40132225, 0.19793269, 0.23231149])

In [28]:
np.random.rand(5,5)

array([[0.70992417, 0.4665437 , 0.45660597, 0.37126553, 0.9888464 ],
       [0.29322053, 0.84191706, 0.291283  , 0.65587684, 0.48901967],
       [0.16932326, 0.69265277, 0.66272088, 0.56000362, 0.67685299],
       [0.72579646, 0.31748651, 0.07876869, 0.41733845, 0.02999818],
       [0.92123145, 0.38701607, 0.57391258, 0.08548771, 0.7066772 ]])

In [31]:
np.random.randn(5)

array([-0.55621674, -0.02346743, -1.00699549, -0.16206616,  0.06011229])

In [32]:
# np.random.normal

In [39]:
np.random.randint(1, 100, 10)

array([67, 11, 70, 61, 82, 96, 44, 74, 55, 45])

In [45]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [46]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [47]:
arr =np.arange(25)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
ranarr =np.random.randint(0,50,10)

In [50]:
ranarr

array([10, 21, 27, 28, 48,  4,  1, 42, 41, 20])

In [52]:
arr.shape

(25,)

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranarr.max()

48

In [55]:
ranarr.min()

1

In [56]:
ranarr.argmin()

6

In [57]:
ranarr.argmax()

4

In [58]:
ranarr.dtype

dtype('int64')